doc-warnings: yes
test-warnings: no
strictness: high
max-line-length: 120
uses:
    - flask
autodetect: yes
requirements:
    - requirements.txt
    - requirements/test.txt
    - requirements/dev.txt
ignore-paths:
    - docs
ignore-patterns:
    - ^example/doc_.*\.py$
    - (^|/)docs(/|$)
python-targets:
    - 3