language: python
python:
  - "3.3"
  - "3.4"
  - "3.5"
install:
  - pip install -r requirements/test.txt
script:
  - PYTHONPATH=. py.test tests --cov auth --cov-report term-missing
after_success:
  - coveralls